name: Rdang
version: '1.2'
main: ru.truhot.rdang.RDang
api-version: '1.16'
author: Truhot
website: https://truhott.github.io/RDang-site/index.html
depend: [WorldGuard, WorldEdit]
commands:
  rdang:
   aliases: [ rd, dang, bdang, adang, edang, holydang ]